### ISSUE TITLE
Design Home Page

### ISSUE THREAD

**Issue by rdidjurgeit** [rdidjurgeit/anchormate#4]
As a user, I can view a home page so that I know I am on the main page of the site.

## Acceptance criteria

- The Home page is accessible from the navigation bar.

- The Home page displays a welcome message or brief app description.

- Layout is consistent with the overall site style.

## TODO

- [x] Design a simple layout for the Home page.

- [x]  Add a welcome message and/or app description.

- [ ]Review page style to ensure it matches the rest of the site.
