### ISSUE TITLE
Implement Login Page

### ISSUE THREAD

**Issue by rdidjurgeit** [rdidjurgeit/anchormate#5]
As a user, I can access a login page so that I can log into my account.

## Acceptance criteria

-Login page is accessible from the navigation bar.

- Login page includes fields for username/email and password.

- Login form redirects to the user’s dashboard upon successful login.

## TODO

- [x] Add a login form template with username and password fields

- [x] Create a link to the login page in the navigation bar.

- [x] API end point to log in

- [x] Implement authentication logic to redirect on successful login
